#!/usr/bin/env bash
set -euo pipefail

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run this script as root (sudo)." >&2
  exit 1
fi

script_dir="$(cd "$(dirname "$0")" && pwd)"
config_path="$script_dir/dnsConf.txt"

if [[ ! -f "$config_path" ]]; then
  echo "Configuration file not found: $config_path" >&2
  exit 1
fi

mapfile -t dns_pairs < <(
  awk -F= '
  {
    name=$1; ip=$2;
    gsub(/[[:space:]]+/, "", name);
    gsub(/[[:space:]]+/, "", ip);
    base=name;
    sub(/[0-9]+$/, "", base);
    if (!(base in seen)) { seen[base]=1; order[++n]=base; }
    count[base]++;
    ips[base,count[base]]=ip;
  }
  END {
    for (i=1;i<=n;i++) {
      b=order[i];
      if (count[b] >= 2) {
        printf "%s|%s|%s\n", b, ips[b,1], ips[b,2];
      }
    }
  }' "$config_path"
)

if [[ ${#dns_pairs[@]} -eq 0 ]]; then
  echo "No DNS pairs found in configuration file." >&2
  exit 1
fi

echo "Select a DNS configuration pair:"
for i in "${!dns_pairs[@]}"; do
  IFS='|' read -r name ip1 ip2 <<< "${dns_pairs[$i]}"
  echo "$((i + 1)). $name ($ip1, $ip2)"
 done

read -r -p "Enter the DNS pair number: " selection
if ! [[ "$selection" =~ ^[0-9]+$ ]]; then
  echo "Invalid selection." >&2
  exit 1
fi

index=$((selection - 1))
if (( index < 0 || index >= ${#dns_pairs[@]} )); then
  echo "Selection out of range." >&2
  exit 1
fi

IFS='|' read -r _ server1 server2 <<< "${dns_pairs[$index]}"

apply_resolvectl_dns() {
  local iface=$1
  resolvectl dns "$iface" "$server1" "$server2"
  resolvectl domain "$iface" "~." || true
}

backup_resolv_conf() {
  if [[ -f /etc/resolv.conf && ! -f /etc/resolv.conf.bak ]]; then
    cp /etc/resolv.conf /etc/resolv.conf.bak
  fi
}

write_resolv_conf() {
  backup_resolv_conf
  {
    echo "# Generated by akaDns"
    echo "nameserver $server1"
    echo "nameserver $server2"
  } > /etc/resolv.conf
}

interfaces=(
  $(ip -o link show up | awk -F': ' '{print $2}' | grep -v '^lo$' || true)
)

if command -v resolvectl >/dev/null 2>&1; then
  if [[ ${#interfaces[@]} -eq 0 ]]; then
    echo "No active network interfaces found." >&2
    exit 1
  fi
  for iface in "${interfaces[@]}"; do
    apply_resolvectl_dns "$iface"
  done
else
  write_resolv_conf
fi

if command -v systemd-resolve >/dev/null 2>&1; then
  systemd-resolve --flush-caches || true
fi

if command -v resolvectl >/dev/null 2>&1; then
  resolvectl flush-caches || true
fi

echo "DNS configuration completed successfully!"
echo "Please test your connection and DNS settings."
