#!/usr/bin/env bash
set -euo pipefail

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run this script as root (sudo)." >&2
  exit 1
fi

script_dir="$(cd "$(dirname "$0")" && pwd)"
export AKA_DNS_HTML="$script_dir/dns-gui.html"
export AKA_DNS_CONFIG="$script_dir/dnsConf.txt"
export AKA_DNS_PORT="8080"

python3 - <<'PY'
import json
import os
import re
import subprocess
from http.server import BaseHTTPRequestHandler, HTTPServer

HTML_PATH = os.environ["AKA_DNS_HTML"]
CONFIG_PATH = os.environ["AKA_DNS_CONFIG"]
PORT = int(os.environ.get("AKA_DNS_PORT", "8080"))

IP_PATTERN = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")


def command_exists(cmd):
    return subprocess.call(["bash", "-lc", f"command -v {cmd} >/dev/null 2>&1"]) == 0


def list_interfaces():
    if not command_exists("ip"):
        return []
    output = subprocess.check_output(["ip", "-o", "link", "show", "up"], text=True)
    interfaces = []
    for line in output.splitlines():
        parts = line.split(": ")
        if len(parts) >= 2:
            iface = parts[1]
            if iface != "lo":
                interfaces.append(iface)
    return interfaces


def read_dns_config():
    entries = []
    if not os.path.exists(CONFIG_PATH):
        return entries
    with open(CONFIG_PATH, "r", encoding="utf-8") as handle:
        for line in handle:
            if "=" in line:
                name, ip = line.split("=", 1)
                entries.append({"name": name.strip(), "ip": ip.strip()})
    return entries


def get_current_dns():
    if command_exists("resolvectl"):
        output = subprocess.check_output(["resolvectl", "dns"], text=True)
        servers = []
        for line in output.splitlines():
            servers.extend(IP_PATTERN.findall(line))
        unique = []
        for ip in servers:
            if ip not in unique:
                unique.append(ip)
        return unique[:3]

    if os.path.exists("/etc/resolv.conf"):
        with open("/etc/resolv.conf", "r", encoding="utf-8") as handle:
            servers = []
            for line in handle:
                if line.strip().startswith("nameserver"):
                    parts = line.split()
                    if len(parts) >= 2:
                        servers.append(parts[1])
            return servers[:3]
    return []


def backup_resolv_conf():
    if os.path.exists("/etc/resolv.conf") and not os.path.exists("/etc/resolv.conf.bak"):
        subprocess.check_call(["cp", "/etc/resolv.conf", "/etc/resolv.conf.bak"])


def write_resolv_conf(servers):
    backup_resolv_conf()
    with open("/etc/resolv.conf", "w", encoding="utf-8") as handle:
        handle.write("# Generated by akaDns\n")
        for server in servers:
            handle.write(f"nameserver {server}\n")


def apply_dns(servers):
    interfaces = list_interfaces()
    if command_exists("resolvectl") and interfaces:
        for iface in interfaces:
            subprocess.check_call(["resolvectl", "dns", iface] + servers)
            subprocess.call(["resolvectl", "domain", iface, "~."])
    else:
        write_resolv_conf(servers)

    if command_exists("resolvectl"):
        subprocess.call(["resolvectl", "flush-caches"])
    if command_exists("systemd-resolve"):
        subprocess.call(["systemd-resolve", "--flush-caches"])


def restore_dns():
    interfaces = list_interfaces()
    if command_exists("resolvectl") and interfaces:
        help_text = subprocess.check_output(["resolvectl", "--help"], text=True, stderr=subprocess.STDOUT)
        revert_supported = "revert" in help_text
        for iface in interfaces:
            if revert_supported:
                subprocess.call(["resolvectl", "revert", iface])
            else:
                subprocess.call(["resolvectl", "dns", iface, ""])
                subprocess.call(["resolvectl", "domain", iface, ""])
    else:
        if os.path.exists("/etc/resolv.conf.bak"):
            subprocess.check_call(["cp", "/etc/resolv.conf.bak", "/etc/resolv.conf"])

    if command_exists("resolvectl"):
        subprocess.call(["resolvectl", "flush-caches"])
    if command_exists("systemd-resolve"):
        subprocess.call(["systemd-resolve", "--flush-caches"])


class Handler(BaseHTTPRequestHandler):
    def _send_json(self, payload, status=200):
        data = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        if self.path == "/current-dns":
            self._send_json({"dns": get_current_dns()})
            return
        if self.path == "/dns-config":
            self._send_json(read_dns_config())
            return

        if os.path.exists(HTML_PATH):
            with open(HTML_PATH, "rb") as handle:
                content = handle.read()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(content)))
            self.end_headers()
            self.wfile.write(content)
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        if self.path not in ("/set-dns", "/restore-dns"):
            self.send_response(404)
            self.end_headers()
            return

        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else b"{}"

        if self.path == "/set-dns":
            payload = json.loads(body.decode("utf-8"))
            servers = [server for server in payload.get("dns", []) if server]
            if not servers:
                self._send_json({"success": False, "message": "No DNS servers provided."}, status=400)
                return
            apply_dns(servers)
            self._send_json({"success": True, "message": "DNS settings updated successfully!"})
            return

        if self.path == "/restore-dns":
            restore_dns()
            self._send_json({"success": True, "message": "DNS settings have been restored to default configuration!"})


server = HTTPServer(("0.0.0.0", PORT), Handler)
print(f"DNS Configuration GUI is running at http://localhost:{PORT}/")
try:
    server.serve_forever()
finally:
    server.server_close()
PY
